### PR TITLE
Fixes  #305 After changing datasource settings requests fail with exception

### LINKED ISSUE #305: After changing datasource settings requests fail with exception
After changing the datasource settings the SOS throws an exception:
`org.hibernate.service.UnknownServiceException: Unknown service requested [org.hibernate.engine.jdbc.connections.spi.ConnectionProvider]`

### PR DESCRIPTION
**Pull request by CarstenHollmann**
Before the HibernateSessionHolder was initiated for each DAO/Handler class with the data connection provider during startup.
Now, always call Configurator.getInstance().getDataConnectionProvider() to get the currently defined data connection provider.

### CODE REVIEW

File: hibernate/session-factory/src/main/java/org/n52/sos/ds/hibernate/HibernateSessionHolder.java [hunk 1]
```diff
@@ -41,16 +41,9 @@
  */
 public class HibernateSessionHolder {
 
-    private final ConnectionProvider connectionProvider;
-
     public HibernateSessionHolder() {
-        this(Configurator.getInstance().getDataConnectionProvider());
     }
     
-    public HibernateSessionHolder(ConnectionProvider connectionProvider) {
```
Comment (autermann) [inline hibernate/session-factory/src/main/java/org/n52/sos/ds/hibernate/HibernateSessionHolder.java]: I think you're breaking the TS API here...
