### PR TITLE
Fix 383 delete complex observation

### LINKED ISSUE #383: Deleting Complex Observation
Hello,

I used the client examples to InsertSensor (sml2.0, sos2.0, pox), and InsertObservation(complex).  I added the <gml:identifier> element to the template, and after it had been added successfully, I attempted to remove the observation using DeleteObservation call with the identifier element value I added.  This throws the following:
```
<!DOCTYPE html><html><head><title>Apache Tomcat/8.0.14 (Ubuntu) - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 500 - </h1><div class="line"></div><p><b>type</b> Exception report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b></p><pre>java.lang.NullPointerException
	org.n52.sos.ds.hibernate.dao.observation.series.AbstractSeriesDAO.updateSeriesAfterObservationDeletion(AbstractSeriesDAO.java:433)
	org.n52.sos.ext.deleteobservation.DeleteObservationDAO.checkSeriesForFirstLatest(DeleteObservationDAO.java:143)
	org.n52.sos.ext.deleteobservation.DeleteObservationDAO.deleteObservation(DeleteObservationDAO.java:93)
	org.n52.sos.ext.deleteobservation.DeleteObservationRequestOperator.receive(DeleteObservationRequestOperator.java:62)
	org.n52.sos.ext.deleteobservation.DeleteObservationRequestOperator.receive(DeleteObservationRequestOperator.java:50)
	org.n52.sos.request.operator.AbstractRequestOperator.receiveRequest(AbstractRequestOperator.java:166)
	org.n52.sos.request.operator.AbstractTransactionalRequestOperator.receiveRequest(AbstractTransactionalRequestOperator.java:68)
	org.n52.sos.service.operator.AbstractServiceOperator.receiveRequest(AbstractServiceOperator.java:61)
	org.n52.sos.binding.PoxBinding.doPostOperation(PoxBinding.java:73)
	org.n52.sos.service.SosService.doPost(SosService.java:140)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
	org.n52.sos.service.ConfiguratedHttpServlet.service(ConfiguratedHttpServlet.java:53)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:186)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:168)
	com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:233)
</pre><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/8.0.14 (Ubuntu) logs.</u></p><hr class="line"><h3>Apache Tomcat/8.0.14 (Ubuntu)</h3></body></html>
```

When I tried using DeleteSensor on the procedure the complex observation was added under, followed by 'admin->delete deleted observations', I can see that the parent observation has been deleted, but the child observations have not, and they have not been marked as deleted either (though the series tuples referenced by the fk are marked as deleted in the series table).

Using commit (d553311baff3ca3123634ae435848ba4a6b02ab0), I haven't have the opportunity to try with a newer commit.

### PR DESCRIPTION
**Pull request by CarstenHollmann**
Fixes #383 
Now the complex observations and the parameter are deleted if you execute delete deleted observations in the admin interface

### CODE REVIEW

File: extensions/do/hibernate/src/main/java/org/n52/sos/ext/deleteobservation/DeleteObservationDAO.java [hunk 1]
```diff
@@ -81,21 +82,17 @@ public synchronized DeleteObservationResponse deleteObservation(DeleteObservatio
...
+			if (observation != null) {
+				deleteObservation(observation, session);
+				so = HibernateObservationUtilities
+						.createSosObservationsFromObservations(Collections.<Observation<?>> singleton(observation),
+								getRequest(request), null, session)
+						.iterator().next();
+			} else {
+				throw new InvalidParameterValueException(DeleteObservationConstants.PARAMETER_NAME,
+						request.getObservationIdentifier());
+			}
```
Comment (autermann) [inline extensions/do/hibernate/src/main/java/org/n52/sos/ext/deleteobservation/DeleteObservationDAO.java]: Intendation!

Comment (CarstenHollmann) [inline extensions/do/hibernate/src/main/java/org/n52/sos/ext/deleteobservation/DeleteObservationDAO.java]: @autermann Updated as you mentioned
